### ISSUE TITLE
Excessive Gas Usage in `xrETH` Due to Debugging `console.log` Statements

### ISSUE THREAD

**Issue by zZoMROT** [nodeset-org/constellation#428]
**Description:**

The current  [implementation](https://etherscan.io/address/0xac24d450e72d3cd27355981ead0fa1ffa611ec1b#code) of [xrETH](https://github.com/nodeset-org/constellation/blob/main/deployments/constellation-mainnet-deployment-10-11-2024.txt#L33) contains four `console.log` debug statements. These statements are resulting in unnecessary static calls to an address where no code exists. This redundancy is causing a notable increase in gas consumption:

- The first static call consumes an extra **2000 gas**.
- Each subsequent call consumes an additional **100 gas**.
- Additionally, three redundant reads are performed to retrieve data for these logs, adding another **300 gas**.

**Impact:** 

This results in a total overhead of approximately **2700 gas** per method call that relies on this logic.

**Request:** 

Please update implementation to remove or disable these debug `console.log` statements to optimize gas usage, benefiting all calls that invoke this method.

<img width="1215" alt="Снимок экрана 2024-11-13 в 21 27 02" src="https://github.com/user-attachments/assets/0348edaa-c25e-4fa7-a117-18106a7be1c3">

**Comment by VVander** [comment]
@zZoMROT thanks for reporting! Looks like this was an oversight from the local project on the machine where we did the deployment since this specific file is part of the OZ libraries and is ignored in our repo. This should be fixed in the upcoming 1.0.1 update.
